### ISSUE TITLE
Quirky behaviour when generating Lists with multiple calls to TheLast(1)

### ISSUE THREAD

**Issue by kuhlschrank** [nbuilder/nbuilder#20] opened 2014-02-25 08:41 UTC
Hi,
first of all I love using NBuilder! Thanks for your work!
But...

[EDIT: Please see post 2 for a more precise explanation of the problem.]

I recently found a behaviour that I can't explain. I have a class RepricingItem that has auto properties SellerId and SalePrice amongst others.
When I build lists like the following...

```
        var listA = Builder<RepricingItem>.CreateListOfSize(3)
            .All()
                .With(x => x.SellerId = 123)
            .TheLast(1)
                .With(x => x.SalePrice = 70m)
            .TheLast(1)
                .With(x => x.SalePrice = 60m)
            .Build();

        var listB = Builder<RepricingItem>.CreateListOfSize(3)
            .TheLast(1)
                .With(x => x.SalePrice = 70m)
            .TheLast(1)
                .With(x => x.SalePrice = 60m)
            .Build();
```

... I perceive a strange behaviour.
listA[2] and listB[2] do NOT have the same SalePrice Property.
listA[2].SalePrice is 70m, whereas listB[2].SalePrice is 60m.

The difference in both list-builds is just the All()-call to a completely unrelated property in listA.

Is there any explanation for this behaviour or did I just stumble upon a bug here?
Thanks for any responses! Hopefully somebody can still here me... :)

(The double-TheLast(1) of listA is done because I want to return a IListBuilder<RepricingItem> from a function that sets "default" values for multiple test cases. The second TheLast(1) is the specific test case.)

**Comment by crmckenzie** [comment] 2018-07-07 18:28
Unable to reproduce. Must have been addressed by an earlier bug.

**Closed by crmckenzie** 2018-07-07 18:28 UTC
Labels: Bug, Discussion
